<?php
    $categoria = $dados[0];
?>

<section class="card card-body">
    <h1>Editar curso</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome: </label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $categoria->nome?>">
                <button class="btn btn-outline-dark w-100">Enviar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>