<section class="card card-body">
    <h1>Nova Categoria</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome da categoria</label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">
                </select>
                
                <button class="btn btn-outline-dark w-100">Cadastrar categoria</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>