<?php
    $aluno = $dados[0];
?>

<section class="card card-body">
    <h1>Editar aluno</h1>

    <div class="row">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome: </label>
                <input name="nome" type="text" id="nome" class="form-control mb-3" value="<?php echo $aluno->nome; ?>">
                <label for="cpf">CPF: </label>
                <input name="cpf" type="text" id="cpf" class="form-control mb-3" minlength="11" maxlength="11" value="<?php echo $aluno->cpf; ?>">
                <label for="email">E-mail:</label>
                <input name="email" type="text" id="email" class="form-control mb-3" value="<?php echo $aluno->email; ?>">
                <label for="genero">Genero: </label>
                <select name="genero" id="genero" class="form-select mb-3" required>
                    <option disabled><?php echo $aluno->genero; ?></option>
                    <option>Masculino</option>
                    <option>Feminino</option>
                    <option>Prefiro não responder</option>
                    <option>Outros</outros>
                </select>
                <label for="dataNascimento">Data de Nascimento: </label>
                <input name="dataNascimento" type="date" id="dataNascimento" class="form-control mb-3" value="<?php echo $aluno->dataNascimento; ?>">

                <button class="btn btn-outline-dark w-100">Enviar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>