<section class="mt-3  card card-body">
    <h1>Gerenciar Alunos</h1>
    <div class="mt-2" >
        <a href="/alunos/listar" class="btn btn-outline-dark">Novo Aluno</a>
    </div>
    <table class="table table-striped table-hover mt-4  table-bordered align-middle text-center">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Matricula</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            if(isset($alunos) && sizeof($alunos) > 0){
                foreach($alunos as $aluno){
                    echo"
                    <tr>
                        <td>{$aluno->id}</td>
                        <td>{$aluno->nome}</td>
                        <td>{$aluno->matricula}</td>
                        <td>{$aluno->cpf}</td>
                        <td>{$aluno->email}</td>
                        <td>
                            <button class='btn btn-outline-warning '>editar</button>
                            <button class='btn btn-outline-danger '>excluir</button>
                        </td>
                    </tr>
                    ";
                }
            }
            ?>
        </tbody>
    </table>
</section>