<section class="mt-3  card card-body">
    <h1>Gerenciar Alunos</h1>
    <div class="mt-2" >
        <a href="/alunos/novo" class="btn btn-outline-dark">Novo Aluno</a>
        <a href="/alunos/relatorio" class="btn btn-outline-dark">Gerar PDF</a>
    </div>
    
    <table class="table table-striped table-hover mt-4  table-bordered align-middle text-center">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Matricula</th>
                <th>CPF</th>
                <th>Email</th>
                <th>Data de Nascimento</th>
                <th>genero</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php 
                foreach($alunos ?? [] as $aluno){
                    echo"
                    <tr>
                        <td>{$aluno->id}</td>
                        <td>{$aluno->nome}</td>
                        <td>{$aluno->matricula}</td>
                        <td>{$aluno->cpf}</td>
                        <td>{$aluno->email}</td>
                        <td>{$aluno->dataNascimento}</td>
                        <td>{$aluno->genero}</td>
                        <td>
                            <a href='/alunos/editar?id={$aluno->id}' class='btn btn-outline-warning btn-sm'>editar</a>
                            <a href='/alunos/excluir?id={$aluno->id}' class='btn btn-outline-danger btn-sm'>excluir</a>
                        </td>
                    </tr>
                    ";
                }
            ?>
        </tbody>
    </table>
</section>