<section class="mt-3  card card-body">
    <h1>Gerenciar Professores</h1>
    <div class="mt-2" >
        <a href="/professores/listar" class="btn btn-outline-dark">Novo Professor</a>
    </div>
    <table class="table table-striped table-hover mt-4 table-bordered align-middle text-center">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Formação</th>
                <th>Endereço</th>
                <th>CPF</th>
                <th>Ações</th>
            </tr>
        </thead>
        <tbody>
            <?php
            if(isset($professores) && sizeof($professores) > 0){
                foreach($professores as $professor)
                echo"
                <tr>
                    <td>{$professor->id}</td>            
                    <td>{$professor->nome}</td>            
                    <td>{$professor->formacao}</td>         
                    <td>{$professor->endereco}</td>              
                    <td>{$professor->cpf}</td>
                    <td>
                    <button class='btn btn-outline-warning '>editar</button>
                    <a href='/professores/excluir?id={$professor->id}' class='btn btn-outline-danger '>excluir</a>
                    </td>        
                </tr>
                ";
            }
            ?>
        </tbody>
    </table>
</section>