<nav class="container-fluid d-flex w-100 pt-3 pb-3 align-items-center bg-dark">
    <div class="d-flex pt-2 w-100">
        <h3 class="text-white">ESCOLA</h3>
    </div>
    <div class="d-flex justify-content-center gap-1">
        <ul class="m-auto list-group list-group-horizontal">
            <li class="list-group-item rounded p-0"><a href="/" class="btn btn-outline-dark">Inicio</a></li>
        </ul>
        <ul class="m-auto list-group list-group-horizontal text-white">
            <li class="list-group-item rounded p-0"><a href="/alunos/listar" class="btn btn-outline-dark">Alunos</a></li>
        </ul> 
        <ul class="m-auto list-group list-group-horizontal text-white">  
            <li class="list-group-item rounded p-0"><a href="/professores/listar" class="btn btn-outline-dark">Professores</a></li>
        </ul>
       
            <ul class="me-auto ms-auto list-group list-group-horizontal text-white">
                <li class="list-group-item rounded p-0"><a href="/cursos/listar" class="btn btn-outline-dark">Cursos</a></li>
            </ul>
            <ul class="list-group list-group-horizontal text-white">
                <li class="list-group-item rounded p-0"><a href="/categorias/listar" class="btn btn-outline-dark">Categorias</a></li>
            </ul>
      
    </div>
    <div class="w-100 d-flex justify-content-end gap-3">
        
        <ul class="list-group">
            <li class="list-group-item me-2 rounded p-0"><a href="/desconectar" class="btn btn-outline-danger">Desconectar</a></li>
        </ul>
    </div>
</nav>