<section class="card card-body">
    <h1>Novo usuario</h1>

    <div class="row ">
        <div class="col">
            <form action="" method="POST">
                <label for="nome">Nome: </label>
                <input name="nome" type="text" id="nome" class="form-control mb-3">
                <label for="email">E-mail:</label>
                <input name="email" type="text" id="email" class="form-control mb-3">
                <label for="senha">Senha: </label>
                <input name="senha" type="text" id="senha" class="form-control mb-3">
                <label for="perfil">Perfil: </label>
                <select name="perfil" id="perfil" class="form-select mb-3">
                    <option disabled selected>-- Selecione --</option>
                    <option value="Normal">Normal</option>
                    <option value="Admin">Admin</outros>
                </select>
                
                <button class="btn btn-outline-dark w-100">Enviar</button>
            </form>
        </div>
        <div class="col"></div>
    </div>
</section>