<section class="mt-3  card card-body">
    <h1>Gerenciar cursos</h1>
    <div class="mt-2" >
        <a href="/cursos/listar" class="btn btn-outline-dark">Meus cursos</a>
    </div>
    <table class="table table-striped table-hover mt-4">
        <thead class="table-dark">
            <tr>
                <th>#ID</th>
                <th>Nome</th>
                <th>Carga Horaria</th>
                <th>Descrição</th>
                <th>Status</th>
                <th>Ementass</th>
            </tr>
        </thead>
        <tbody>
            
        </tbody>
    </table>
</section>